image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages: 
    - build
    - deploy

before_script:
    - "dotnet restore"
    
build:
    stage: build
    script:
        - "dotnet build"

deploy:
    stage: deploy
    script:
        - "echo 'Deplod'"